### PR TITLE
Allow players to resolve their own tickets

### PR DESCRIPTION
**Pull request by LeBulldoge**
#### Brief overview of PR changes/additions
Added a `/close` switch to `request`, letting players close their own tickets and supply a resolution.
#### Motivation for adding to Arx
Should help reduce ticket bloat
#### Other info (issues closed, discussion etc)
Closing #357

### CODE REVIEW

**Comment by LeBulldoge** [comment]
Also fixed the failing test in the stable branch, which was caused by the `rating` field being no longer required in `ClueCreateForm`, though not sure if the fix is correct, the test might be outdated.

And I don't really agree with/understand the remaining lint checks, one of them is even complaining about a migration file. :o

**Comment by TehomCD** [comment]
Oh the github action for black can't be pinned to a version anymore due to some upstream issue, so if someone wisely decided to change indentation in a new version or whatever everything explodes. I'll see about fixing that at some point today

**Comment by LeBulldoge** [comment]
Alrighty, thanks. I believe everything should be ironed out now.

**Review by TehomCD — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
