### PR TITLE
Adding @adjust command

### PR DESCRIPTION
**Pull request by dvoraen**
#### Brief overview of PR changes/additions
Addition of a new staff command, @adjust.

#### Motivation for adding to Arx
Making some staff tasks a little easier.

#### Other info (issues closed, discussion etc)
See +request 26099 for full context.

I am not 100% sure I have the correct method invocation for the adjustment to silver/materials/resources.  Testing showed that there was a bug with offline characters, so I made an adjustment and that tested fine for offline characters.  Would appreciate a bit of scrutiny on the "account.method()" calls that I made.  My major concern is the award/deduction going to the wrong alt somehow.  (If multiple chars are on the same account, who gets it?)

### CODE REVIEW

**Comment by dvoraen** [comment]
The Coveralls issue baffles me.  It started recently on my fork out of nowhere but I have no idea what's causing it to be rejected.  I'd been hoping it was just specific to my fork rather than everything.  Will fix the Codacy thing right now.

**Comment by TehomCD** [comment]
Not sure why coveralls is suddenly breaking. Regenerating the coveralls token didn't fix it, could try removing the github secret token from its env in workflows and seeing if that was interfering for god knows what reason

**Comment by dvoraen** [comment]
> Not sure why coveralls is suddenly breaking. Regenerating the coveralls token didn't fix it, could try removing the github secret token from its env in workflows and seeing if that was interfering for god knows what reason

I'm so confused with what's going on with Coveralls.  It failed with the same error (HTTP 422) on my personal commit but EVERYTHING'S FINE here.

**Review by TehomCD — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
